# Generated by Django 2.1.6 on 2019-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
