# Generated by Django 2.1.6 on 2019-02-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_board_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='organizations.Organization'),
        ),
    ]
